### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by xGenius123** [Monifactory/MAE2#9]
Just a quick question:

Is 1.21 in consideration or was this made for the sole purpose of Monifactory?

**Comment by xGenius123** [comment]
@AE2-Enthusiast

**Comment by AE2-Enthusiast** [comment]
I've talked about this before in the Discord, but I'm not inherently opposed to porting to other versions. Except I'm doing this for fun and porting involves messing with gradle and other annoying tasks, so I'm probably never gonna get around to that. I tried once and immediately ran into gradle issues, but maybe I'll try again when I update to ModDevGradle or whatever the new thing is.
